joefitzgerald/go-plus

styles/go-plus.atom-text-editor.less
Right now the following deprecation warnings are being produced:
* Use the `atom-text-editor` tag instead of the `editor` class.
* Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.
=> Switch from the editor CSS class to the atom-text-editor class

lib/gobuild.coffee
(was breaking go-to-error functionality)
It should have been matchLine[5].substring(1, 3)... use path.isAbsolute instead.
=> Fix absolute path detection under windows

lib/go-plus.coffee, lib/gocodeprovider.coffee
autocomplete-plus was activating on `,`, `:`, and `}`. I couldn't come up with
a reason why anyone would want to complete on those characters so I
added them to the list. Forgive me if this is bad coffeescript...
Fixes #177
=> Ignore more types of whitespace

README.md
autocomplete-plus is bundled with Atom since 0.199.0, so this step is no longer necessary.
=> Remove step to install autocomplete-plus

examples/godef/hasDefinitions.go, keymaps/go-plus.cson, lib/dispatch.coffee, lib/go.coffee, lib/godef.coffee, lib/goexecutable.coffee, spec/godef-spec.coffee, stylesheets/go-plus.less
Adds a new command to go-plus, `golang:godef`, bound at this stage to cmd-opt-g.The behaviour is:
- if invoked on an identifier bound at package scope in the same file, jumps cursor to the (highlighted) declaration
- if invoked on an identifier bound to an identifier declared in an import package, opens the declaring file in a new tab, and puts the cursor on the (highlighted) declaration
There are some minor oddities in godef's output in some cases. I've just special-cased these, and a message panel will pop up to explain to the user why nothing appears to be happening.
This is written and tested on a mac; haven't had a chance yet to try it on any other platform.
Fixes #123.
=> Godef command

.travis.yml, appveyor.yml
This package is now bundled with Atom and doesn't need to be installed separately.
Resolves the following build warning:
>The autocomplete-plus package is bundled with Atom and should not be explicitly installed.
You can run `apm uninstall autocomplete-plus` to uninstall it and then the version bundled
with Atom will be used.
=> Remove autocomplete-plus install from CI scripts.

lib/godef.coffee
The` GOPATH` set in the package settings is not being use when `godef` is run.
=> Fix issue were godef didn't set GOPATH

lib/goexecutable.coffee
The godef package has been moved to github (see http://godoc.org/code.google.com/p/rog-go/exp/cmd/godef).  This change will allow Get Missing Tools to install it.
=> updated godef package location

keymaps/go-plus.cson, lib/executor.coffee, lib/godef.coffee, lib/util/editor-location-stack.coffee, spec/godef-spec.coffee
go-plus' current godef integration is limited to top-level and exported names,
and does not work for method calls:
buf := bytes.Buffer{}
buf.Write([]byte{0x0}) // godef on Write and buf didn't work.
This is because godef was being run as:
godef -f filebeingedited.go buf.Write
which doesn't give godef enough context to know what "buf" and "Write" are.
The fix is to run godef with the offset (-o) option to give it the offset
in the file where the cursor is, and let godef figure out what the user's
trying to navigate to.
This commit also keeps track of godef navigation on a stack and allows going
back to previous locations where godef was triggered with the godef-return
command.
=> Better godef integration: local defs, imports

lib/godef.coffee, spec/godef-spec.coffee
My previous update to use godef's -o option passed in UTF-16 (Javascript
string) offsets to godef, which wants byte offsets in the source file. Give
godef the UTF-8 offset instead (since Go requires that source files must be
encoded in UTF-8).
(Switched to Buffer.byteLength to save allocating a new Buffer that's then immediately thrown away)
=> godef: handle multibyte UTF-8 codepoints

README.md, package.json
Haven't touched CI scripts `.travis.yml` and `appveyor.yml`.
=> add go-debug

lib/components/go-plus-panel.js, lib/panel-manager.js
- Allows a view provider to determine if it is currently active, so that it can avoid work
=> Allow View Providers To Determine When The Panel Is Shown And The Tab Is Active

.travis.yml, README.md, appveyor.yml, keymaps/go-plus.json, lib/formatter.js, lib/main.js, menus/go-plus.json, package.json, spec/fixtures/gofmt.go, spec/formatter-spec.js
=> Merge gofmt back into go-plus

lib/tester.js
Currently stderr output is not always visible. I feel it is always useful to see it, especially when tests fail.
In any case, thank you for awesome plugin!
=> Always show stderr output

styles/overrides.less
This adds an `overrides.less` file with some custom styling for the Material UI theme.
Closes #519
=> Customize material theme

lib/config/environment.js, spec/config/environment-spec.js, spec/config/locator-spec.js
- Make use of it for any go version
Fixes #547
=> Add support for the default GOPATH in go 1.8+

lib/navigator/godef.js, spec/navigator/godef-spec.js
It currently fails if the cursor is at the end of a word:
```go
fmt.Println ("hello world")
//         ↑ if cursor is here between `ln` and `(` it fails
```
Solution: call guru with `position.column - 1` (simply step back 1 character)
=> Improve navigation with guru

.travis.yml, appveyor.yml, keymaps/go-plus.json, lib/main.js, lib/package-manager.js, lib/tags/gomodifytags.js, lib/tags/tags-dialog.js, spec/fixtures/gomodifytags/foo.go, spec/tags/gomodifytags-spec.js, styles/gomodifytags.less
This PR adds support for @fatih's new `gomodifytags` tool.  
Two new commands are exposed: `golang:add-tags` and `golang:remove-tags`.  These can be used to automatically add/remove struct tags.  The UI offers options for specifying tags and their options, whether to use `snake_case` or `camelCase` for the tag names, and the ability to sort the tags.
A brief demo: (sorry about the super-speed gif)
The behavior is similar to that of [vim-go](https://github.com/fatih/vim-go/pull/1204).
If the cursor is inside a struct and there is no selection, the tool operates on the entire struct.
If there is a selection then the tool only operates on line(s) that are touched by the selection (you don't need to select the entire line).
If no tags are given then `json` is the default.  You can specify …
=> New feature: modify struct tags

lib/build/builder.js, lib/config/executor.js, lib/test/tester.js, package.json, spec/doc/godoc-spec.js, spec/navigator/godef-spec.js, spec/rename/gorename-spec.js, spec/tags/gomodifytags-spec.js, spec/test/gocover-parser-spec.js, spec/test/tester-spec.js
Remove dependency on rimraf since fs-extra's `remove` function
performs the same duties.
Closes #572, #567, #566, #553, #552
=> :arrow-up: dependencies

lib/test/tester.js, package.json
- Allows the user to disable coverage while still running tests
This is helpful when printing log output, and you want to see accurate source lines:
```
log.SetFlags(log.Llongfile)
log.Printf("hello world")
```
Coverage performs source rewriting to collect coverage information, which throws the line numbers off.
Fixes #588
=> Add runTestsWithCoverage flag

lib/implements/implements-view.js, lib/usage/usage-view.js
Having a look into etch shows that this isn't even supported: https://github.com/atom/etch/blob/v0.12.3/lib/component-helpers.js#L95-L97
Also got rid of unnecessary `console.log`s
fixes #631
=> Do not use different DOM nodes as the root for the usage view

lib/build/builder.js
Fix for #644 
1. `result.output` needs additional checking otherwise an empty string `""` results in `true`
2. If `result.output` is empty check if errorcode 124 is present, if so show time-out message
Note that the line (just after this fix)
```
return Promise.reject(new Error(result.output));
```
results in `builder.js [sm]:84 Uncaught (in promise) Error:` in the developer console.
I am no go-plus/promises expert, so I am unable to fix this... (so feel free to fix this in this PR if you actually know what is happening :wink: )
=> Show time-out message when build times out

keymaps/go-plus.json, lib/test/tester.js, spec/tags/gomodifytags-spec.js
I toggle the config for `go-plus.test.runTestsWithCoverage` enough times each day that I found myself annoyed at having to open Atom settings to toggle the config. 
This PR adds a command (`golang:toggle-test-with-coverage`) and a keybinding (<kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>shift</kbd> + <kbd>g</kbd>&nbsp;&nbsp;<kbd>c</kbd>) to run the command.
=> Add command to toggle the config for running tests with coverage

lib/autocomplete/gocodeprovider.js, lib/build/builder.js, lib/tags/gomodifytags.js, lib/tags/tags-dialog.js, package-lock.json, package.json, spec/autocomplete/gocodeprovider-spec.js, spec/tags/gomodifytags-spec.js
Don't merge this yet - would like to use it for a while and make sure everything works well.
Two changes here:
1. don't generate snippet tab stops for `...args` - these are often optional arguments and a tab stop disrupts the workflow.
2. support fuzzy matching, which has been requested numerous times over the past few years
For the fuzzy matching, we actually improve performance by calling gocode less.  We only invoke gocode when a `.` is entered or a new word begins, and we cache the results from that run.  For future keypresses, we refine the original set of suggestions using fuzzaldrin-plus.
=> improve autocomplete provider

lib/test/tester.js
The current behavior is to only show coverage when tests fail. This is an unnecessary restriction - we should allow coverage to be shown whenever the coverage file contains valid information.
Note: This does not allow coverage to be shown for a focused [ginkgo](https://github.com/onsi/ginkgo) spec, as the coverage file does not appear to be generated when any focusing occurs. See https://github.com/onsi/ginkgo/issues/205 for more details 😢.
=> Show test coverage if go test’s exit code is non-zero

lib/test/tester.js
/[^/\\]+$/g finds the filename given a Windows or OS X path. We then
filter editorRanges to include those where the filenames on file and
r.file match, excluding _test.go files
=> allow test coverage for symlinks

lib/tags/tags-dialog.js
Altered the "Add Tags" command to take any text in the input boxes and use that text if there are no other tags defined.
The change is intended to improve the user experience and decrease confusion whenever a user is adding a single custom struct tag that doesn't use default values (tag:"json", options:"").
Fixes #692
*Note: There aren't currently any tests for the `TestDialog` so there aren't any tests in this PR. I can try to add something, but my JS skills are limited and I'm not 100% familiar with the proper way to add a new test, especially one on a UI component. Testing in the [gomodifytags-spec.js](https://github.com/joefitzgerald/go-plus/blob/master/spec/tags/gomodifytags-spec.js) doesn't appear to be plausible since these tests seem to start after the `TestDialog` would have …
=> Use input text for "Add Tags" command when no opts specified.

.travis.yml, appveyor.yml, lib/autocomplete/gocodeprovider-helper.js, lib/autocomplete/gocodeprovider.js, lib/config/executor.js, lib/go.js, lib/package-manager.js, spec/autocomplete/gocodeprovider-helper-spec.js, spec/autocomplete/gocodeprovider-spec.js
This is done by (temporarily) adding an `import "..."` statement into the code so that `gocode` can find the package and provide suggestions for it.
It is still rough on the edges especially for vendored packages.
Possible improvements:
* automatically add the `import "..."` when a suggestion is selected (nice to have, will be added by `goimports` on save anyway)
* the `pkg` map in `go.js` does not grow if new packages are added (low prio)
Fixes #665
=> autocomplete unimported packages

lib/package-manager.js
Fixes #682. Added a bundledAlt map to check for alternative packages. Also changed verbiage of linter message since atom-ide-ui is maintained by Atom now.
=> Check for atom-ide in package manager, fixes #682

lib/build/builder.js, lib/test/tester.js, package.json, spec/test/tester-spec.js
Add option `go-plus.config.compileOnSave` that defaults to true.
When disabled, go plus will not attempt to build your code when a file is saved.
In this mode, go-plus will only format the file on save, which can be helpful if for some reason local compilation would fail (see #674).
Additionally, we make the assumption that if the user doesn't want to compile on save, they also don't want to test on save (if local compilation would fail, local test runs would also fail), and so we never run tests on save if compile on save is disabled.
=> add option to disable compilation on save

lib/build/builder.js, lib/test/tester.js, package.json, spec/build/builder-spec.js, spec/test/tester-spec.js
Introduce `go-plus.config.additional{Build|Test}Args` config properties that allow users to alter the flags that are passed to:
build args:
- go build / go install
- go test -c
test args:
- go test -coverprofile
This can be used to define build tags, for example.
- Fixes #282
- Fixes #308
- Fixes #551
- Fixes #573
- Fixes #690
- Closes #565
=> add config options for addditional build/test args

README.md, lib/autocomplete/gocodeprovider.js, package.json
Remove calls to `gocode set`
mdempsky/gocode doesn't support this operation.
You can now request builtins by using -builtin.
There is not currently an option to enable completions for unimported packages.
=> Better compatibility with mdempsky/gocode

lib/format/formatter.js, spec/format/formatter-spec.js
We previously aborted the format operation if there was output on stderr.
Fixes #600
=> Always use formatter result when exit code is 0

README.md, lib/lint/linter.js, lib/main.js, lib/package-manager.js, package.json
This PR introduces support for support [`revive`](https://github.com/mgechev/revive)and [`golangci-lint`](https://github.com/golangci/golangci-lint) linters in addition to [`gometalinter`](https://github.com/alecthomas/gometalinter)
closes #819
=> support revive and golangci-lint linters

lib/doc/godoc.js
Inline code had the side effect that any struct tags like \`json:"test"\` broke the layout of the code.
Using code blocks it now renders everything as it should including indentation and even proper highlighting if the datatip plugin understands that.
=> use code blocks instead of inline code for datatips

lib/package-manager.js
* https://github.com/mdempksy/gocode does not support `go modules`
* https://github.com/stamblerre/gocode does support `go modules` and has become the defacto `gocode` implementation
This PR switches from `mdempsky` to `stamblerre`. Note that this may introduce a small amount of additional latency when working in `GOPATH` (as opposed to a `go module`), however the go team continue to optimize the functionality of `go list`, `go/packages`, and `stamblerre/gocode`.
=> use github.com/stamblerre/gocode to get go module compatibility
